spring:
  profiles:
    active: local
  main:
    banner-mode: # "off"
  batch:
    job:
      names: ${job.name:NONE}
  jpa:
    show-sql: false
    properties.hibernate.format_sql: false

mybatis:
  type-aliases-package: com.kt.mmp.setl.setlCalc.domain

logging:
  level:
    com.kt.spring: DEBUG
    org.springframework.batch: INFO

---
spring:
  profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver

---
spring:
  profile: postgres
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/blogdb
      username: blogown
      password: new1234!
      driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
